export const transactions = [
  {
    id: 1,
    date: "2025-09-15",
    type: "credit",
    description: "BRIGHTON FILMS ACTING PAYMENT",
    transac: "ACH TRANSFER",
    amount: 218500,
  },
  {
    id: 2,
    date: "2025-09-18",
    type: "debit",
    description: "CLOTHING INVENTORY PURCHASE",
    transac: "ACH PAYMENT",
    amount: 122451,
  },
  {
    id: 3,
    date: "2025-09-22",
    type: "debit",
    description: "APARTMENT RENT PAYMENT",
    transac: "CHECK",
    amount: 43850,
  },
  {
    id: 4,
    date: "2025-09-25",
    type: "credit",
    description: "ONLINE FASHION STORE SALES",
    transac: "ACH CREDIT",
    amount: 148675,
  },
  {
    id: 5,
    date: "2025-10-02",
    type: "debit",
    description: "FILM STUDIO BOOKING FEE",
    transac: "DEBIT CARD",
    amount: 15260,
  },
  {
    id: 6,
    date: "2025-10-07",
    type: "credit",
    description: "WILLOWBROOK TALENT GROUP MODELING FEE",
    transac: "WIRE TRANSFER",
    amount: 164750,
  },
  {
    id: 7,
    date: "2025-10-12",
    type: "debit",
    description: "WOMENSWEAR SUPPLIER PAYMENT",
    transac: "ACH PAYMENT",
    amount: 87935,
  },
  {
    id: 8,
    date: "2025-10-18",
    type: "debit",
    description: "HEALTH COVERAGE PREMIUM",
    transac: "ACH DEBIT",
    amount: 7842,
  },
  {
    id: 9,
    date: "2025-10-24",
    type: "credit",
    description: "FASHION BOUTIQUE SALES",
    transac: "ACH CREDIT",
    amount: 292181,
  },
  {
    id: 10,
    date: "2025-11-03",
    type: "debit",
    description: "INSTAGRAM PROMOTION CHARGE",
    transac: "DEBIT CARD",
    amount: 20186,
  },
  {
    id: 11,
    date: "2025-11-10",
    type: "credit",
    description: "TNORTHSTAR PICTURES RESIDUAL PAYMENT",
    transac: "ACH CREDIT",
    amount: 91750,
  },
  {
    id: 12,
    date: "2025-11-15",
    type: "debit",
    description: "WINTER APPAREL STOCK ORDER",
    transac: "WIRE TRANSFER",
    amount: 125780,
  },
  {
    id: 13,
    date: "2025-11-22",
    type: "debit",
    description: "RESIDENTIAL LEASE PAYMENT",
    transac: "CHECK",
    amount: 43850,
  },
  {
    id: 14,
    date: "2025-12-01",
    type: "credit",
    description: "HOLIDAY COLLECTION REVENUE",
    transac: "ACH CREDIT",
    amount: 341751,
  },
  {
    id: 15,
    date: "2025-12-06",
    type: "debit",
    description: "DOMESTIC TRAVEL EXPENSE",
    transac: "DEBIT CARD",
    amount: 15840,
  },
  {
    id: 16,
    date: "2025-12-14",
    type: "credit",
    description: "LUMEN FASHION HOUSE CAMPAIGN FEE",
    transac: "WIRE TRANSFER",
    amount: 18200,
  },
  {
    id: 17,
    date: "2025-12-20",
    type: "debit",
    description: "QUARTERLY BUSINESS TAX",
    transac: "ACH DEBIT",
    amount: 86650,
  },
  {
    id: 18,
    date: "2026-01-03",
    type: "credit",
    description: "SILVERLINE STUDIOS ACTING FEE",
    transac: "ACH CREDIT",
    amount: 42500,
  },
  {
    id: 19,
    date: "2026-01-09",
    type: "debit",
    description: "NEW COLLECTION PRODUCTION",
    transac: "WIRE TRANSFER",
    amount: 19875,
  },
  {
    id: 20,
    date: "2026-01-17",
    type: "debit",
    description: "VEHICLE LEASE INSTALLMENT",
    transac: "ACH DEBIT",
    amount: 1285,
  },
  {
    id: 21,
    date: "2026-01-24",
    type: "credit",
    description: "MENSWEAR ONLINE ORDERS",
    transac: "ACH CREDIT",
    amount: 26891,
  },
  {
    id: 22,
    date: "2026-02-05",
    type: "debit",
    description: "EDITORIAL PHOTO SESSION",
    transac: "DEBIT CARD",
    amount: 3275,
  },
  {
    id: 23,
    date: "2026-02-13",
    type: "credit",
    description: "EVERGREEN STYLE AGENCY MODELING FEE",
    transac: "WIRE TRANSFER",
    amount: 23600,
  },
  {
    id: 24,
    date: "2026-02-21",
    type: "debit",
    description: "APPAREL WHOLESALE ORDER",
    transac: "ACH PAYMENT",
    amount: 11241,
  },
  {
    id: 25,
    date: "2026-03-02",
    type: "debit",
    description: "FEDERAL ESTIMATED TAX",
    transac: "ACH DEBIT",
    amount: 14750,
  },
  {
    id: 26,
    date: "2026-03-11",
    type: "credit",
    description: "HARBORLIGHT ENTERTAINMENT ACTING PAYMENT",
    transac: "ACH CREDIT",
    amount: 58750,
  },
  {
    id: 27,
    date: "2026-04-04",
    type: "debit",
    description: "SPRING INVENTORY RESTOCK",
    transac: "WIRE TRANSFER",
    amount: 22480,
  },
  {
    id: 28,
    date: "2026-05-08",
    type: "credit",
    description: "SPRING COLLECTION PROCEEDS",
    transac: "ACH CREDIT",
    amount: 34676,
  },
  {
    id: 29,
    date: "2026-06-16",
    type: "debit",
    description: "TALENT MANAGEMENT FEE",
    transac: "CHECK",
    amount: 5840,
  },
  {
    id: 30,
    date: "2026-07-02",
    type: "credit",
    description: "CRESCENT MEDIA PRODUCTIONS ACTING FEE",
    transac: "WIRE TRANSFER",
    amount: 37500,
  },
  {
    id: 31,
    date: "2026-07-19",
    type: "debit",
    description: "SUMMER LINE MANUFACTURING",
    transac: "ACH PAYMENT",
    amount: 18640,
  },
  {
    id: 32,
    date: "2026-08-03",
    type: "credit",
    description: "CRESCENT MEDIA PRODUCTIONS ACTING FEE",
    transac: "ACH CREDIT",
    amount: 79481,
  },
  {
    id: 33,
    date: "2026-08-21",
    type: "debit",
    description: "BUSINESS SOFTWARE EXPENSE",
    transac: "DEBIT CARD",
    amount: 4266,
  },
  {
    id: 39,
    date: "2026-09-03",
    type: "credit",
    description: "GOVT GRANT",
    transac: "WIRE TRANSFER",
    amount: 250000,
  },
  {
    id: 34,
    date: "2026-09-05",
    type: "credit",
    description: "MONARCH MODEL MANAGEMENT FEE",
    transac: "WIRE TRANSFER",
    amount: 46800,
  },
  {
    id: 35,
    date: "2026-09-15",
    type: "credit",
    description: "DIRECT TO CONSUMER SALES",
    transac: "ACH CREDIT",
    amount: 18750,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2025-09-16",
    type: "credit",
    description: "MONTHLY RESERVE CONTRIBUTION",
    transac: "INTERNAL TRANSFER",
    amount: 215000,
  },
  {
    id: 2,
    date: "2025-09-28",
    type: "credit",
    description: "CLOTHING BUSINESS SURPLUS",
    transac: "ACH TRANSFER",
    amount: 128500,
  },
  {
    id: 3,
    date: "2025-10-05",
    type: "debit",
    description: "PERSONAL EXPENSE TRANSFER",
    transac: "INTERNAL TRANSFER",
    amount: 73500,
  },
  {
    id: 4,
    date: "2025-10-19",
    type: "credit",
    description: "ACTING INCOME ALLOCATION",
    transac: "INTERNAL TRANSFER",
    amount: 32000,
  },
  {
    id: 5,
    date: "2025-10-31",
    type: "credit",
    description: "ANNUAL SAVINGS YIELD",
    transac: "INTEREST CREDIT",
    amount: 17486,
  },
  {
    id: 6,
    date: "2025-11-08",
    type: "credit",
    description: "BUSINESS RESERVE FUNDING",
    transac: "ACH TRANSFER",
    amount: 287500,
  },
  {
    id: 7,
    date: "2025-11-20",
    type: "debit",
    description: "CHECKING ACCOUNT FUNDING",
    transac: "INTERNAL TRANSFER",
    amount: 192000,
  },
  {
    id: 8,
    date: "2025-11-30",
    type: "credit",
    description: "MONTH END INTEREST EARNINGS",
    transac: "INTEREST CREDIT",
    amount: 20515,
  },
  {
    id: 9,
    date: "2025-12-09",
    type: "credit",
    description: "HOLIDAY SALES ALLOCATION",
    transac: "ACH TRANSFER",
    amount: 412500,
  },
  {
    id: 10,
    date: "2025-12-28",
    type: "debit",
    description: "CLOTHING BUSINESS WITHDRAWAL",
    transac: "INTERNAL TRANSFER",
    amount: 125000,
  },
  {
    id: 11,
    date: "2025-12-31",
    type: "credit",
    description: "YEAR END INTEREST CREDIT",
    transac: "INTEREST CREDIT",
    amount: 2347,
  },
  {
    id: 12,
    date: "2026-01-07",
    type: "credit",
    description: "NEW YEAR RESERVE DEPOSIT",
    transac: "INTERNAL TRANSFER",
    amount: 35000,
  },
  {
    id: 13,
    date: "2026-01-21",
    type: "credit",
    description: "ENTERTAINMENT EARNINGS RESERVE",
    transac: "ACH TRANSFER",
    amount: 28000,
  },
  {
    id: 14,
    date: "2026-01-31",
    type: "credit",
    description: "JANUARY ACCOUNT INTEREST",
    transac: "INTEREST CREDIT",
    amount: 286,
  },
  {
    id: 15,
    date: "2026-02-11",
    type: "debit",
    description: "PERSONAL ACCOUNT TRANSFER",
    transac: "INTERNAL TRANSFER",
    amount: 147500,
  },
  {
    id: 16,
    date: "2026-02-26",
    type: "credit",
    description: "APPAREL BUSINESS RESERVE",
    transac: "ACH TRANSFER",
    amount: 36500,
  },
  {
    id: 17,
    date: "2026-02-28",
    type: "credit",
    description: "FEBRUARY INTEREST EARNINGS",
    transac: "INTEREST CREDIT",
    amount: 313,
  },
  {
    id: 18,
    date: "2026-03-14",
    type: "credit",
    description: "PRODUCTION INCOME SAVINGS",
    transac: "INTERNAL TRANSFER",
    amount: 42000,
  },
  {
    id: 19,
    date: "2026-03-29",
    type: "debit",
    description: "PROPERTY RESERVE WITHDRAWAL",
    transac: "INTERNAL TRANSFER",
    amount: 152500,
  },
  {
    id: 20,
    date: "2026-03-31",
    type: "credit",
    description: "MARCH INTEREST ACCRUAL",
    transac: "INTEREST CREDIT",
    amount: 349,
  },
  {
    id: 21,
    date: "2026-04-09",
    type: "credit",
    description: "QUARTERLY BUSINESS SAVINGS",
    transac: "ACH TRANSFER",
    amount: 48500,
  },
  {
    id: 22,
    date: "2026-04-25",
    type: "debit",
    description: "OPERATING CASH TRANSFER",
    transac: "INTERNAL TRANSFER",
    amount: 26000,
  },
  {
    id: 23,
    date: "2026-04-30",
    type: "credit",
    description: "APRIL INTEREST PAYMENT",
    transac: "INTEREST CREDIT",
    amount: 375,
  },
  {
    id: 24,
    date: "2026-05-13",
    type: "credit",
    description: "SUMMER COLLECTION RESERVE",
    transac: "ACH TRANSFER",
    amount: 52000,
  },
  {
    id: 25,
    date: "2026-05-27",
    type: "debit",
    description: "BUSINESS EXPANSION FUNDING",
    transac: "INTERNAL TRANSFER",
    amount: 178500,
  },
  {
    id: 26,
    date: "2026-05-31",
    type: "credit",
    description: "MAY SAVINGS EARNINGS",
    transac: "INTEREST CREDIT",
    amount: 49822,
  },
  {
    id: 27,
    date: "2026-06-18",
    type: "credit",
    description: "MIDYEAR INCOME TRANSFER",
    transac: "INTERNAL TRANSFER",
    amount: 47500,
  },
  {
    id: 28,
    date: "2026-06-30",
    type: "credit",
    description: "JUNE INTEREST ALLOCATION",
    transac: "INTEREST CREDIT",
    amount: 47868,
  },
  {
    id: 29,
    date: "2026-07-11",
    type: "credit",
    description: "MEDIA EARNINGS RESERVE",
    transac: "ACH TRANSFER",
    amount: 38500,
  },
  {
    id: 30,
    date: "2026-07-26",
    type: "debit",
    description: "MONTHLY CASH FLOW TRANSFER",
    transac: "INTERNAL TRANSFER",
    amount: 14500,
  },
  {
    id: 31,
    date: "2026-07-31",
    type: "credit",
    description: "JULY INTEREST EARNED",
    transac: "INTEREST CREDIT",
    amount: 513,
  },
  {
    id: 32,
    date: "2026-08-12",
    type: "credit",
    description: "FASHION BUSINESS PROFITS",
    transac: "ACH TRANSFER",
    amount: 44000,
  },
  {
    id: 33,
    date: "2026-08-29",
    type: "credit",
    description: "PERSONAL RESERVE CONTRIBUTION",
    transac: "INTERNAL TRANSFER",
    amount: 32500,
  },
  {
    id: 34,
    date: "2026-08-31",
    type: "credit",
    description: "AUGUST INTEREST CREDIT",
    transac: "INTEREST CREDIT",
    amount: 546,
  },
  {
    id: 35,
    date: "2026-09-15",
    type: "credit",
    description: "CLOTHING REVENUE ALLOCATION",
    transac: "ACH TRANSFER",
    amount: 58750,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
  // { id: 4, label: "Previous Years", value: "730" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
