export const transactions = [
  {
    id: 1,
    date: "2025-04-05",
    type: "credit",
    description: "ETF DIVIDEND DISTRIBUTION",
    transac: "ACH",
    amount: 1180000,
  },
  {
    id: 2,
    date: "2025-08-09",
    type: "debit",
    description: "INVESTMENT ADVISORY FEE",
    transac: "ACH",
    amount: 3200,
  },
  {
    id: 3,
    date: "2025-08-15",
    type: "credit",
    description: "MUNICIPAL BOND COUPON PAYMENT",
    transac: "DEPOSIT",
    amount: 42000,
  },
  {
    id: 4,
    date: "2025-08-22",
    type: "debit",
    description: "BROKERAGE FUNDING TRANSFER",
    transac: "TRANSFER",
    amount: 75000,
  },
  {
    id: 5,
    date: "2025-09-03",
    type: "credit",
    description: "REAL ESTATE FUND DISTRIBUTION",
    transac: "WIRE",
    amount: 95000,
  },
  {
    id: 6,
    date: "2025-09-12",
    type: "debit",
    description: "FEDERAL ESTIMATED TAX PAYMENT",
    transac: "ACH",
    amount: 28000,
  },
  {
    id: 7,
    date: "2025-09-20",
    type: "credit",
    description: "TREASURY NOTE INTEREST",
    transac: "DEPOSIT",
    amount: 18000,
  },
  {
    id: 8,
    date: "2025-09-28",
    type: "debit",
    description: "PRIVATE EQUITY CAPITAL CALL",
    transac: "WIRE",
    amount: 60000,
  },
  {
    id: 9,
    date: "2025-10-06",
    type: "credit",
    description: "STOCK SALE SETTLEMENT",
    transac: "WIRE",
    amount: 125000,
  },
  {
    id: 10,
    date: "2025-10-10",
    type: "debit",
    description: "TRANSFER TO SAVINGS",
    transac: "TRANSFER",
    amount: 100000,
  },
  {
    id: 11,
    date: "2025-10-18",
    type: "credit",
    description: "REIT CASH DISTRIBUTION",
    transac: "ACH",
    amount: 34000,
  },
  {
    id: 12,
    date: "2025-10-24",
    type: "debit",
    description: "PROPERTY MANAGEMENT EXPENSE",
    transac: "ACH",
    amount: 5200,
  },
  {
    id: 13,
    date: "2025-11-04",
    type: "credit",
    description: "INDEX FUND CAPITAL GAIN",
    transac: "ACH",
    amount: 56000,
  },
  {
    id: 14,
    date: "2025-11-08",
    type: "debit",
    description: "COMMERCIAL PROPERTY INSPECTION",
    transac: "CHECK",
    amount: 2800,
  },
  {
    id: 15,
    date: "2025-11-19",
    type: "credit",
    description: "COVERED CALL OPTION PREMIUM",
    transac: "DEPOSIT",
    amount: 22000,
  },
  {
    id: 16,
    date: "2025-11-27",
    type: "debit",
    description: "WIRE TO TITLE COMPANY",
    transac: "WIRE",
    amount: 45000,
  },
  {
    id: 17,
    date: "2025-12-05",
    type: "credit",
    description: "PRIVATE CREDIT FUND INCOME",
    transac: "WIRE",
    amount: 78000,
  },
  {
    id: 18,
    date: "2025-12-14",
    type: "debit",
    description: "TRANSFER TO SAVINGS",
    transac: "TRANSFER",
    amount: 125000,
  },
  {
    id: 19,
    date: "2026-01-06",
    type: "credit",
    description: "BROKERAGE CASH SWEEP CREDIT",
    transac: "ACH",
    amount: 27000,
  },
  {
    id: 20,
    date: "2026-01-16",
    type: "debit",
    description: "REAL ESTATE ESCROW PAYMENT",
    transac: "WIRE",
    amount: 85000,
  },
  {
    id: 21,
    date: "2026-02-03",
    type: "credit",
    description: "CAPITAL GAIN DISTRIBUTION",
    transac: "WIRE",
    amount: 110000,
  },
  {
    id: 22,
    date: "2026-02-11",
    type: "debit",
    description: "PORTFOLIO MANAGEMENT FEE",
    transac: "ACH",
    amount: 4100,
  },
  {
    id: 23,
    date: "2026-03-05",
    type: "credit",
    description: "ENERGY FUND DISTRIBUTION",
    transac: "ACH",
    amount: 49000,
  },
  {
    id: 24,
    date: "2026-03-18",
    type: "debit",
    description: "STATE ESTIMATED TAX PAYMENT",
    transac: "ACH",
    amount: 24000,
  },
  {
    id: 25,
    date: "2026-04-07",
    type: "credit",
    description: "COMMERCIAL PROPERTY SALE PROCEEDS",
    transac: "WIRE",
    amount: 160000,
  },
  {
    id: 26,
    date: "2026-04-19",
    type: "debit",
    description: "ALTERNATIVE INVESTMENT FUNDING",
    transac: "WIRE",
    amount: 95000,
  },
  {
    id: 27,
    date: "2026-05-06",
    type: "credit",
    description: "INTERNATIONAL ETF DISTRIBUTION",
    transac: "ACH",
    amount: 85000,
  },
  {
    id: 28,
    date: "2026-05-24",
    type: "debit",
    description: "TRANSFER TO SAVINGS",
    transac: "TRANSFER",
    amount: 150000,
  },
  {
    id: 29,
    date: "2026-06-12",
    type: "credit",
    description: "PRIVATE EQUITY RETURN OF CAPITAL",
    transac: "WIRE",
    amount: 135000,
  },
  {
    id: 30,
    date: "2026-06-17",
    type: "debit",
    description: "LUXURY VEHICLE DOWN PAYMENT",
    transac: "ACH",
    amount: 199495,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2025-05-10",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "TRANSFER",
    amount: 1100000,
  },
  {
    id: 2,
    date: "2025-08-31",
    type: "credit",
    description: "HIGH YIELD INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 22500,
  },
  {
    id: 3,
    date: "2025-09-05",
    type: "debit",
    description: "TREASURY BILL PURCHASE",
    transac: "TRANSFER",
    amount: 530000,
  },
  {
    id: 4,
    date: "2025-09-30",
    type: "credit",
    description: "MONEY MARKET INTEREST",
    transac: "DEPOSIT",
    amount: 24600,
  },
  {
    id: 5,
    date: "2025-10-08",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "TRANSFER",
    amount: 755000,
  },
  {
    id: 6,
    date: "2025-10-15",
    type: "debit",
    description: "BOND LADDER INVESTMENT",
    transac: "TRANSFER",
    amount: 465000,
  },
  {
    id: 7,
    date: "2025-10-31",
    type: "credit",
    description: "TREASURY INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 27750,
  },
  {
    id: 8,
    date: "2025-11-07",
    type: "credit",
    description: "REINVESTMENT ACCOUNT DEPOSIT",
    transac: "ACH",
    amount: 282000,
  },
  {
    id: 9,
    date: "2025-11-18",
    type: "debit",
    description: "REAL ESTATE ESCROW RESERVE",
    transac: "WIRE",
    amount: 690000,
  },
  {
    id: 10,
    date: "2025-11-30",
    type: "credit",
    description: "SAVINGS INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 20800,
  },
  {
    id: 11,
    date: "2025-12-10",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "TRANSFER",
    amount: 1125987,
  },
  {
    id: 12,
    date: "2025-12-31",
    type: "credit",
    description: "MUNICIPAL FUND INCOME",
    transac: "DEPOSIT",
    amount: 3000,
  },
  {
    id: 13,
    date: "2026-01-06",
    type: "debit",
    description: "TREASURY NOTE ACQUISITION",
    transac: "TRANSFER",
    amount: 70000,
  },
  {
    id: 14,
    date: "2026-01-12",
    type: "credit",
    description: "HIGH YIELD INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 3150,
  },
  {
    id: 15,
    date: "2026-01-15",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "TRANSFER",
    amount: 90000,
  },
  {
    id: 16,
    date: "2026-01-20",
    type: "debit",
    description: "PRIVATE CREDIT ALLOCATION",
    transac: "WIRE",
    amount: 80000,
  },
  {
    id: 17,
    date: "2026-01-28",
    type: "credit",
    description: "MONEY MARKET EARNINGS",
    transac: "DEPOSIT",
    amount: 3300,
  },
  {
    id: 18,
    date: "2026-02-10",
    type: "credit",
    description: "CASH RESERVE DEPOSIT",
    transac: "ACH",
    amount: 45000,
  },
  {
    id: 19,
    date: "2026-02-28",
    type: "credit",
    description: "TREASURY INTEREST PAYMENT",
    transac: "DEPOSIT",
    amount: 3450,
  },
  {
    id: 20,
    date: "2026-03-08",
    type: "debit",
    description: "PROPERTY ACQUISITION RESERVE",
    transac: "WIRE",
    amount: 90000,
  },
  {
    id: 21,
    date: "2026-03-30",
    type: "credit",
    description: "SAVINGS YIELD CREDIT",
    transac: "DEPOSIT",
    amount: 3600,
  },
  {
    id: 22,
    date: "2026-04-06",
    type: "credit",
    description: "TRANSFER FROM CHECKING",
    transac: "TRANSFER",
    amount: 150000,
  },
  {
    id: 23,
    date: "2026-04-31",
    type: "credit",
    description: "CASH MANAGEMENT INTEREST",
    transac: "DEPOSIT",
    amount: 3750,
  },
  {
    id: 24,
    date: "2026-05-10",
    type: "debit",
    description: "FIXED INCOME INVESTMENT PURCHASE",
    transac: "TRANSFER",
    amount: 65000,
  },
  {
    id: 25,
    date: "2026-05-30",
    type: "credit",
    description: "TREASURY INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 3900,
  },
  {
    id: 26,
    date: "2026-06-05",
    type: "credit",
    description: "CAPITAL PRESERVATION DEPOSIT",
    transac: "ACH",
    amount: 55000,
  },
  {
    id: 27,
    date: "2026-06-06",
    type: "debit",
    description: "WEALTH MANAGEMENT ALLOCATION",
    transac: "WIRE",
    amount: 85000,
  },
  {
    id: 28,
    date: "2026-06-10",
    type: "credit",
    description: "LIQUIDITY RESERVE CONTRIBUTION",
    transac: "TRANSFER",
    amount: 70000,
  },
  {
    id: 29,
    date: "2026-06-14",
    type: "credit",
    description: "HIGH YIELD INTEREST CREDIT",
    transac: "DEPOSIT",
    amount: 4100,
  },
  {
    id: 30,
    date: "2026-06-16",
    type: "credit",
    description: "LONG TERM RESERVE ADJUSTMENT",
    transac: "DEPOSIT",
    amount: 120000,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
  // { id: 4, label: "Previous Years", value: "730" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
