export const transactions = [
  {
    id: 1,
    date: "2025-08-05",
    type: "credit",
    description: "ACH CREDIT HVAC INSTALLATION INVOICE",
    transac: "ACH Deposit",
    amount: 650,
  },
  {
    id: 2,
    date: "2025-08-07",
    type: "debit",
    description: "DEBIT CARD BUILDING MATERIALS",
    transac: "Debit Card",
    amount: 1843,
  },
  {
    id: 3,
    date: "2025-08-11",
    type: "debit",
    description: "ONLINE BILL PAY ELECTRIC SERVICE",
    transac: "Online Payment",
    amount: 287,
  },
  {
    id: 4,
    date: "2025-08-15",
    type: "credit",
    description: "MOBILE CHECK CUSTOMER PAYMENT",
    transac: "Mobile Deposit",
    amount: 375,
  },
  {
    id: 5,
    date: "2025-08-20",
    type: "debit",
    description: "FUEL STATION PURCHASE",
    transac: "Debit Card",
    amount: 94,
  },
  {
    id: 6,
    date: "2025-09-02",
    type: "credit",
    description: "COMMERCIAL MAINTENANCE CONTRACT",
    transac: "ACH Deposit",
    amount: 720,
  },
  {
    id: 7,
    date: "2025-09-06",
    type: "debit",
    description: "WORK VEHICLE INSURANCE PREMIUM",
    transac: "ACH Debit",
    amount: 142,
  },
  {
    id: 8,
    date: "2025-09-10",
    type: "debit",
    description: "ATM CASH WITHDRAWAL",
    transac: "ATM",
    amount: 30,
  },
  {
    id: 9,
    date: "2025-09-18",
    type: "credit",
    description: "WIRE RECEIVED PROJECT MILESTONE",
    transac: "Wire",
    amount: 510,
  },
  {
    id: 10,
    date: "2025-10-01",
    type: "debit",
    description: "TOOL EQUIPMENT PURCHASE",
    transac: "Debit Card",
    amount: 1685,
  },
  {
    id: 11,
    date: "2025-10-04",
    type: "credit",
    description: "SEASONAL HVAC SERVICE COLLECTION",
    transac: "ACH Deposit",
    amount: 865,
  },
  {
    id: 12,
    date: "2025-10-08",
    type: "debit",
    description: "OFFICE INTERNET PAYMENT",
    transac: "Online Payment",
    amount: 94,
  },
  {
    id: 13,
    date: "2025-10-15",
    type: "debit",
    description: "SAFETY EQUIPMENT PURCHASE",
    transac: "Debit Card",
    amount: 427,
  },
  {
    id: 14,
    date: "2025-10-22",
    type: "credit",
    description: "EMERGENCY REPAIR SERVICE",
    transac: "ACH Deposit",
    amount: 280,
  },
  {
    id: 15,
    date: "2025-11-03",
    type: "debit",
    description: "PROPERTY TAX PAYMENT",
    transac: "Online Payment",
    amount: 200,
  },
  {
    id: 16,
    date: "2025-11-06",
    type: "credit",
    description: "NEW CONSTRUCTION HVAC PAYMENT",
    transac: "Wire",
    amount: 1400,
  },
  {
    id: 17,
    date: "2025-11-12",
    type: "debit",
    description: "WAREHOUSE RENT PAYMENT",
    transac: "ACH Debit",
    amount: 150,
  },
  {
    id: 18,
    date: "2025-11-18",
    type: "debit",
    description: "MOBILE PHONE BILL",
    transac: "Online Payment",
    amount: 189,
  },
  {
    id: 19,
    date: "2025-12-02",
    type: "credit",
    description: "CUSTOM HVAC FABRICATION ORDER",
    transac: "ACH Deposit",
    amount: 985,
  },
  {
    id: 20,
    date: "2025-12-09",
    type: "debit",
    description: "OFFICE SUPPLIES PURCHASE",
    transac: "Debit Card",
    amount: 264,
  },
  {
    id: 21,
    date: "2025-12-17",
    type: "debit",
    description: "MORTGAGE PAYMENT",
    transac: "ACH Debit",
    amount: 240,
  },
  {
    id: 22,
    date: "2026-01-05",
    type: "credit",
    description: "WINTER HEATING SERVICE PAYMENT",
    transac: "ACH Deposit",
    amount: 730,
  },
  {
    id: 23,
    date: "2026-01-13",
    type: "debit",
    description: "VEHICLE MAINTENANCE EXPENSE",
    transac: "Debit Card",
    amount: 651,
  },
  {
    id: 24,
    date: "2026-02-03",
    type: "credit",
    description: "REFRIGERATION SYSTEM INSTALLATION",
    transac: "Wire",
    amount: 10850,
  },
  {
    id: 25,
    date: "2026-02-12",
    type: "debit",
    description: "STATE LICENSE RENEWAL",
    transac: "Online Payment",
    amount: 250,
  },
  {
    id: 26,
    date: "2026-03-06",
    type: "credit",
    description: "COMMERCIAL COOLING PROJECT",
    transac: "ACH Deposit",
    amount: 9680,
  },
  {
    id: 27,
    date: "2026-03-20",
    type: "debit",
    description: "FEDERAL ESTIMATED TAX PAYMENT",
    transac: "ACH Debit",
    amount: 5500,
  },
  {
    id: 28,
    date: "2026-04-09",
    type: "credit",
    description: "ANNUAL SERVICE AGREEMENT RENEWAL",
    transac: "ACH Deposit",
    amount: 6240,
  },
  {
    id: 29,
    date: "2026-05-15",
    type: "debit",
    description: "TRANSFER TO SAVINGS ACCOUNT",
    transac: "Transfer",
    amount: 4500,
  },
  {
    id: 30,
    date: "2026-07-22",
    type: "credit",
    description: "FINAL CUSTOMER SETTLEMENT",
    transac: "Wire",
    amount: 5840,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2025-08-08",
    type: "credit",
    description: "TRANSFER FROM CHECKING ACCOUNT",
    transac: "Transfer",
    amount: 3000,
  },
  {
    id: 2,
    date: "2025-08-31",
    type: "credit",
    description: "MONTHLY INTEREST CREDIT",
    transac: "Interest",
    amount: 4128,
  },
  {
    id: 3,
    date: "2025-09-10",
    type: "credit",
    description: "EMERGENCY FUND CONTRIBUTION",
    transac: "Transfer",
    amount: 1500,
  },
  {
    id: 4,
    date: "2025-09-30",
    type: "credit",
    description: "QUARTERLY SAVINGS ALLOCATION",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 5,
    date: "2025-10-02",
    type: "debit",
    description: "TRANSFER TO CHECKING ACCOUNT",
    transac: "Transfer",
    amount: 1200,
  },
  {
    id: 6,
    date: "2025-10-31",
    type: "credit",
    description: "HIGH YIELD INTEREST PAYMENT",
    transac: "Interest",
    amount: 463,
  },
  {
    id: 7,
    date: "2025-11-05",
    type: "credit",
    description: "YEAR END RESERVE DEPOSIT",
    transac: "Deposit",
    amount: 4200,
  },
  {
    id: 8,
    date: "2025-11-15",
    type: "credit",
    description: "PROJECT PROFIT ALLOCATION",
    transac: "Transfer",
    amount: 3200,
  },
  {
    id: 9,
    date: "2025-11-30",
    type: "credit",
    description: "MONTHLY INTEREST EARNED",
    transac: "Interest",
    amount: 491,
  },
  {
    id: 10,
    date: "2025-12-03",
    type: "debit",
    description: "HOLIDAY FAMILY EXPENSE",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 11,
    date: "2025-12-20",
    type: "credit",
    description: "LONG TERM CASH RESERVE",
    transac: "Deposit",
    amount: 5000,
  },
  {
    id: 12,
    date: "2025-12-31",
    type: "credit",
    description: "ANNUAL INTEREST CREDIT",
    transac: "Interest",
    amount: 542,
  },
  {
    id: 13,
    date: "2026-01-09",
    type: "credit",
    description: "NEW YEAR SAVINGS CONTRIBUTION",
    transac: "Transfer",
    amount: 2800,
  },
  {
    id: 14,
    date: "2026-01-31",
    type: "credit",
    description: "INTEREST PAYMENT",
    transac: "Interest",
    amount: 587,
  },
  {
    id: 15,
    date: "2026-02-07",
    type: "debit",
    description: "TRANSFER FOR EQUIPMENT PURCHASE",
    transac: "Transfer",
    amount: 3000,
  },
  {
    id: 16,
    date: "2026-02-18",
    type: "credit",
    description: "WINTER PROJECT SAVINGS",
    transac: "Transfer",
    amount: 4600,
  },
  {
    id: 17,
    date: "2026-02-28",
    type: "credit",
    description: "MONTH END INTEREST CREDIT",
    transac: "Interest",
    amount: 612,
  },
  {
    id: 18,
    date: "2026-03-06",
    type: "credit",
    description: "BUSINESS CASH SURPLUS",
    transac: "Deposit",
    amount: 3700,
  },
  {
    id: 19,
    date: "2026-03-19",
    type: "debit",
    description: "TRANSFER FOR TAX RESERVE",
    transac: "Transfer",
    amount: 2200,
  },
  {
    id: 20,
    date: "2026-03-31",
    type: "credit",
    description: "QUARTER END INTEREST",
    transac: "Interest",
    amount: 645,
  },
  {
    id: 21,
    date: "2026-04-08",
    type: "credit",
    description: "SPRING PROJECT PROFIT",
    transac: "Transfer",
    amount: 5100,
  },
  {
    id: 22,
    date: "2026-04-30",
    type: "credit",
    description: "SAVINGS INTEREST CREDIT",
    transac: "Interest",
    amount: 664,
  },
  {
    id: 23,
    date: "2026-05-05",
    type: "debit",
    description: "TRANSFER FOR HOME IMPROVEMENT",
    transac: "Transfer",
    amount: 4000,
  },
  {
    id: 24,
    date: "2026-05-17",
    type: "credit",
    description: "CAPITAL PRESERVATION DEPOSIT",
    transac: "Deposit",
    amount: 6200,
  },
  {
    id: 25,
    date: "2026-05-31",
    type: "credit",
    description: "MONTHLY INTEREST ACCRUAL",
    transac: "Interest",
    amount: 693,
  },
  {
    id: 26,
    date: "2026-06-12",
    type: "credit",
    description: "SUMMER CASH ALLOCATION",
    transac: "Transfer",
    amount: 3500,
  },
  {
    id: 27,
    date: "2026-06-30",
    type: "credit",
    description: "SEMIANNUAL INTEREST CREDIT",
    transac: "Interest",
    amount: 718,
  },
  {
    id: 28,
    date: "2026-07-09",
    type: "credit",
    description: "LONG TERM INVESTMENT RESERVE",
    transac: "Deposit",
    amount: 4400,
  },
  {
    id: 29,
    date: "2026-07-21",
    type: "debit",
    description: "TRANSFER FOR PERSONAL EXPENSES",
    transac: "Transfer",
    amount: 1800,
  },
  {
    id: 30,
    date: "2026-07-29",
    type: "credit",
    description: "FINAL MONTH INTEREST CREDIT",
    transac: "Interest",
    amount: 734,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
  // { id: 4, label: "Previous Years", value: "730" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
